#+title: pdf-meta-edit

Modify PDF metadata. PDF metadata includes the PDF outline, pagination (chronological and actual), and pagination style(s). =pdf-tools= offers powerful commands to navigate PDFs via chronological pagination (~pdf-view-goto-page~), actual pagination (i.e. "labels") (~pdf-view-goto-label~), and outline (~pdf-outline~, or =consult='s ~consult-imenu~). Hence, a PDF's metadata can become very handy---when accurate, at least.

However, many PDFs can have missing or inconsistent metadata, such as having no outline nor labels (i.e. actual pagination). I hadn't found any existing package to do this (and still haven't), so I wrote a few lines of code to leverage Linux's =pdftk= binary. It creates a new buffer whose contents are the output of =pdftk='s representation of PDF metadata. Users can change the buffer contents to their liking then "commit" those changes to the actual file (using =pdftk=).

An early and limited version of this code was first shared [[https://www.reddit.com/r/emacs/comments/1gbkdag/code_to_modify_pdf_metadata_such_as_its_outline/][on the r/emacs subreddit]] as a [[https://gist.github.com/krisbalintona/f4554bb8e53c27c246ae5e3c4ff9b342][GitHub gist]].

* Features

+ Represent PDF bookmarks, labels, and page information as plain-text in Emacs buffers
+ "Commit" changes to pdf bookmarks, labels, and page information
+ Basic font-locking (in ~pdf-meta-edit-mode~ buffers)
+ Add and modify metadata (bookmarks, labels, and page information)
  - Commands which make the addition and modification of metadata easier (see, e.g., ~pdf-meta-edit-bookmark-subsection~ and ~pdf-meta-edit-label-subsection~)
+ Navigation between metadata sections in ~pdf-meta-edit-mode~ buffers

* Related packages

+ [[https://github.com/dalanicolai/doc-tools-toc][dalanicolai/doc-tools-toc]] :: A package which, among other things, provides commands that use external tools OCR, ~mutools~, and [[https://github.com/dalanicolai/doc-tools-toc?tab=readme-ov-file#pdf-tocgen-software-generated-pdfs][pdf-tocgen]] to extract table of contents text from PDFs.

* Roadmap

+ [X] Explicitly select parameters for labels
+ [ ] Font-locking with more visual clarity
+ [ ] A "follow" mode between the bookmark or label at point and the pdf
+ [ ] Automatic generation of bookmarks based on table of contents page(s)
+ [ ] Implementation of ~cpdf~ CLI tool

* Changelog

** 0.1.0

+ Added function to represent PDF metadata in plain-text, insert that text into an Emacs buffer, then the ability to "commit" changes made in that buffer to the PDF file itself (~pdf-meta-edit-modify~)
+ Added commands for inserting bookmarks (~pdf-meta-edit-bookmark-subsection~) and labels (~pdf-meta-edit-label-subsection~)
+ Added font-locking
+ Added navigation between metadata sections and subections
